In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [8]:

env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


rewards_all_episodes = []

In [9]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])  # chope la meilleure action
        else:
            action = env.action_space.sample()  # action au hasard

        # Take new action
        new_state, reward, done, info = env.step(action)

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate *
                             np.max(q_table[new_state, :]))

        # Set new state
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * \
        np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

In [5]:
# Calculate and print the average reward per thousand episodes
print(num_episodes / 1000)
print(np.array(rewards_all_episodes))
rewards_per_thousand_episodes = np.split(
    np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

    # Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

10.0
[0. 0. 0. ... 0. 1. 0.]
********Average reward per thousand episodes********

1000 :  0.035000000000000024
2000 :  0.22000000000000017
3000 :  0.4020000000000003
4000 :  0.5640000000000004
5000 :  0.6350000000000005
6000 :  0.6660000000000005
7000 :  0.6550000000000005
8000 :  0.7070000000000005
9000 :  0.6670000000000005
10000 :  0.6770000000000005


********Q-table********

[[0.5549953  0.50308115 0.50256822 0.49741621]
 [0.40009431 0.32236419 0.27385679 0.49345513]
 [0.40315044 0.40172739 0.39011619 0.46033796]
 [0.27032238 0.33052896 0.28666263 0.44213433]
 [0.57618936 0.3792604  0.39674929 0.32514901]
 [0.         0.         0.         0.        ]
 [0.13315715 0.1712554  0.37339201 0.02099024]
 [0.         0.         0.         0.        ]
 [0.34349721 0.37958231 0.33021247 0.62538954]
 [0.46405652 0.6721314  0.47218057 0.49309863]
 [0.58348537 0.42161846 0.35628752 0.3941394 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.4

In [10]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        state = new_state

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break

env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
